server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  resources:
    static-locations: classpath:/static/



mapper:
  mappers: com.yujizi.mapper.BanjiMapper
  identity: MYSQL

